name: Build and Release domainQuery

on:
  push:
    branches:
      - '*'  # 触发所有分支的推送

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Build project
      run: |
        make build-all
        ls -R release/  # 列出 release 目录内容，用于调试

    - name: Generate release tag
      id: tag
      run: |
        echo "release_tag=release_$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: success()
      with:
        files: |
          release/windows-amd64/domainQuery.exe
          release/linux-amd64/domainQuery
          release/darwin-amd64/domainQuery
        tag_name: ${{ steps.tag.outputs.release_tag }}
        name: Release ${{ steps.tag.outputs.release_tag }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
