name: Build and Release domainQuery

on:
  push:
    branches:
      - '*'  # 触发所有分支的推送

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Build project
      run: |
        make build-all # 假设您的Makefile中有build-all命令

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./release/windows-amd64/domainQuery_${{ github.sha }}.exe
          ./release/linux-amd64/domainQuery_${{ github.sha }}
          ./release/darwin-amd64/domainQuery_${{ github.sha }}
        tag_name: ${{ github.sha }}
        name: Release ${{ github.sha }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
